### ISSUE TITLE
Docker Compose v2 Issue

### ISSUE THREAD

**Issue by rtthane** [BassT23/Proxmox#122]
I have just updated to version 4.1 of the script. I can't work out why but this version bypasses docker compose updates. I am running docker compose v2 plugin under /home/user/.docker/cli-plugins.

When i run docker compose version i get
Docker Compose version v2.26.1

When running the script it just goes straight to finished extra updates.

The docker compose v2 .yml file which I use to deploy my stack is located in /home/user/docker/docker-compose.yml

I noticed that there is no COMPOSE=$(find / -name "docker-compose.yml under the docker compose v2 section of the update-extras.sh file. 

The previous version of the script worked fine with my setup. Can you advise how i can resolve this please?

**Comment by BassT23** [comment]
For now, I made a fix, to roll back to "old" v1.8.3 (update-extras.sh):

```
rm -f /etc/ultimate-updater/update-extras.sh && curl -s -L https://raw.githubusercontent.com/BassT23/Proxmox/fix-temp/update-extras.sh > /etc/ultimate-updater/update-extras.sh
```

Hope, this help you for now ;)

**Comment by rtthane** [comment]
> For now, I made a fix, to roll back to "old" v1.8.3 (update-extras.sh):
> 
> ```
> rm -f /etc/ultimate-updater/update-extras.sh && curl -s -L https://raw.githubusercontent.com/BassT23/Proxmox/fix-temp/update-extras.sh > /etc/ultimate-updater/update-extras.sh
> ```
> 
> Hope, this help you for now ;)
> 
> EDIT: stop - there is an error, ... just one moment EDIT2: should work now ;)

Thanks for this. Works fine now :-)

**Comment by BassT23** [comment]
hopefully fixed with latest develop branch.
If you want, feel free to try out with `update develop -up` and give feedback ;)

**Comment by rtthane** [comment]
> hopefully fixed with latest develop branch. If you want, feel free to try out with `update develop -up` and give feedback ;)

Hi, updated to the develop branch. Still doesn't work for me. Under /usr/local/bin i am running docker compose v2.26.1, but the script detects it as docker compose v1

--------------------------------------------------------------

--- Searching for extra updates ---

*** Updating Docker-Compose v1 (oldstable) ***

latest: Pulling from library/traefik
Digest: sha256:7996bdae8aaa70eaacf2978b6c949de5b68c0a24ddc3e40c06344ecc88cfaea3
Status: Image is up to date for traefik:latest
docker.io/library/traefik:latest

*** Updating Docker-Compose v1 (oldstable) ***

no configuration file provided: not found
no configuration file provided: not found
no configuration file provided: not found

*** Updating Docker Compose ***
no configuration file provided: not found
no configuration file provided: not found

--------------------------------------------------------------------

**Comment by Gauvino** [comment]
> > hopefully fixed with latest develop branch. If you want, feel free to try out with `update develop -up` and give feedback ;)
> 
> Hi, updated to the develop branch. Still doesn't work for me. Under /usr/local/bin i am running docker compose v2.26.1, but the script detects it as docker compose v1
> 
> --- Searching for extra updates ---
> 
> *** Updating Docker-Compose v1 (oldstable) ***
> 
> latest: Pulling from library/traefik Digest: sha256:7996bdae8aaa70eaacf2978b6c949de5b68c0a24ddc3e40c06344ecc88cfaea3 Status: Image is up to date for traefik:latest docker.io/library/traefik:latest
> 
> *** Updating Docker-Compose v1 (oldstable) ***
> 
> no configuration file provided: not found no configuration file provided: not found no configuration file provided: not found
> 
> *** Updating Docker Compose *** no configuration file provided: not found no configuration file provided: not found

Could you please remake the command from the official docker install please 
https://docs.docker.com/engine/install/ubuntu/

**Comment by BassT23** [comment]
I see the problem:
the merge dosn't work correctly, ...
give me one moment to fix it

**Comment by BassT23** [comment]
ok, fixed, pls give it a try :)
