### ISSUE TITLE
Interactive questions break update

### ISSUE THREAD

**Issue by jermudgeon** [BassT23/Proxmox#85]
Interactive questions such as 'Automatically restart Docker daemon?', which require a yes/no answer, appear to hang, because keyboard update is not passed to them. My only recourse is to update each node manually. Any thoughts on how to improve this?

**Comment by BassT23** [comment]
I will have a look on this.
Could you please give me a log output from fhe failure?

**Comment by jermudgeon** [comment]
`root@sumia:/var/log# cat update-sumia.log
     https://github.com/BassT23/Proxmox
     ____
    / __ \_________  _  ______ ___  ____  _  __
   / /_/ / ___/ __ \| |/_/ __ `__ \/ __ \| |/_/
  / ____/ /  / /_/ />  </ / / / / / /_/ />  <
 /_/   /_/   \____/_/|_/_/ /_/ /_/\____/_/|_|
      __  __          __      __
     / / / /___  ____/ /___ _/ /____  ____
    / / / / __ \/ __  / __ `/ __/ _ \/ __/
   / /_/ / /_/ / /_/ / /_/ / /_/  __/ /
   \____/ .___/\____/\____/\__/\___/_/
       /_/

            ***  Mode: Cluster ***
            ***   Interactive  ***
             Script is UpToDate
               Version: 3.9


[Info] Updating Host : 192.168.5.211 192.168.1.211 192.168.3.211 192.168.8.211 192.168.8.111 192.168.4.211 10.242.0.164 2602:fbe5:30:10:4ca2:b4ff:fe27:fdd0 2602:fbe5:30:0:4ca2:b4ff:fe27:fdd0 fdb6:78fa:113d:a89f:9199:9355:1b36:5987 fc8b:d065:8055:1b36:5987::1 | (qualb)

--- APT UPDATE ---
Hit:1 http://192.168.1.118/proxmox/mirror/download.proxmox.com/debian/pve bookworm InRelease
Hit:2 http://192.168.1.118/proxmox/mirror/download.proxmox.com/debian/ceph-quincy bookworm InRelease
Hit:3 http://mirrors.acsalaska.net/debian bookworm InRelease
Hit:4 http://mirrors.acsalaska.net/debian bookworm-updates InRelease
Get:5 http://security.debian.org bookworm-security InRelease [48.0 kB]
Hit:6 http://ftp.us.debian.org/debian bookworm InRelease
Hit:7 https://repo.fig.io/apt stable InRelease
Hit:8 http://ftp.us.debian.org/debian bookworm-updates InRelease
Hit:9 https://apt.releases.hashicorp.com bookworm InRelease
Hit:10 http://download.zerotier.com/debian/bookworm bookworm InRelease
Hit:11 http://download.proxmox.com/debian/pve bookworm InRelease
Hit:12 http://download.proxmox.com/debian/ceph-quincy bookworm InRelease
Fetched 48.0 kB in 3s (15.6 kB/s)
Reading package lists...

--- APT UPGRADE ---
Reading package lists...
Building dependency tree...
Reading state information...
Calculating upgrade...
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

--- APT CLEANING ---
Reading package lists...
Building dependency tree...
Reading state information...
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

--- Check Status for Welcome-Screen ---
Host : qualb
 Reboot required
---          Finished check         ---


[Info] Backup Skipped by user for LXC 103
[Info] Updating LXC 103 : tardis

--- APT UPDATE ---
Hit:1 https://apt.releases.hashicorp.com jammy InRelease
Hit:2 http://download.zerotier.com/debian/jammy jammy InRelease
Hit:3 http://us.archive.ubuntu.com/ubuntu jammy InRelease
Get:4 http://us.archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]
Get:5 http://us.archive.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Fetched 229 kB in 2s (141 kB/s)
Reading package lists...
W: https://apt.releases.hashicorp.com/dists/jammy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
W: http://download.zerotier.com/debian/jammy/dists/jammy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.

--- APT UPGRADE ---
Reading package lists...
Building dependency tree...
Reading state information...
Calculating upgrade...
The following packages will be upgraded:
  bind9-dnsutils bind9-host bind9-libs consul dnsutils
5 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 67.2 MB of archives.
After this operation, 1,473 kB of additional disk space will be used.
Get:1 https://apt.releases.hashicorp.com jammy/main amd64 consul amd64 1.17.0-1 [65.8 MB]
Get:2 http://us.archive.ubuntu.com/ubuntu jammy-updates/main amd64 bind9-host amd64 1:9.18.18-0ubuntu0.22.04.1 [52.5 kB]
Get:3 http://us.archive.ubuntu.com/ubuntu jammy-updates/main amd64 bind9-dnsutils amd64 1:9.18.18-0ubuntu0.22.04.1 [157 kB]
Get:4 http://us.archive.ubuntu.com/ubuntu jammy-updates/main amd64 bind9-libs amd64 1:9.18.18-0ubuntu0.22.04.1 [1,244 kB]
Get:5 http://us.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 dnsutils all 1:9.18.18-0ubuntu0.22.04.1 [3,928 B]
dpkg-preconfigure: unable to re-open stdin: No such file or directory
Fetched 67.2 MB in 16s (4,206 kB/s)
(Reading database ... 56411 files and directories currently installed.)
Preparing to unpack .../bind9-host_1%3a9.18.18-0ubuntu0.22.04.1_amd64.deb ...
Unpacking bind9-host (1:9.18.18-0ubuntu0.22.04.1) over (1:9.18.12-0ubuntu0.22.04.3) ...
Preparing to unpack .../bind9-dnsutils_1%3a9.18.18-0ubuntu0.22.04.1_amd64.deb ...
Unpacking bind9-dnsutils (1:9.18.18-0ubuntu0.22.04.1) over (1:9.18.12-0ubuntu0.22.04.3) ...
Preparing to unpack .../bind9-libs_1%3a9.18.18-0ubuntu0.22.04.1_amd64.deb ...
Unpacking bind9-libs:amd64 (1:9.18.18-0ubuntu0.22.04.1) over (1:9.18.12-0ubuntu0.22.04.3) ...
Preparing to unpack .../consul_1.17.0-1_amd64.deb ...
Unpacking consul (1.17.0-1) over (1.16.2-1) ...
Preparing to unpack .../dnsutils_1%3a9.18.18-0ubuntu0.22.04.1_all.deb ...
Unpacking dnsutils (1:9.18.18-0ubuntu0.22.04.1) over (1:9.18.12-0ubuntu0.22.04.3) ...
Setting up bind9-libs:amd64 (1:9.18.18-0ubuntu0.22.04.1) ...
Setting up consul (1.17.0-1) ...

Configuration file '/etc/consul.d/consul.hcl'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** consul.hcl (Y/I/N/O/D/Z) [default=N] ? dpkg: error processing package consul (--configure):
 end of file on stdin at conffile prompt
Setting up bind9-host (1:9.18.18-0ubuntu0.22.04.1) ...
Setting up bind9-dnsutils (1:9.18.18-0ubuntu0.22.04.1) ...
Setting up dnsutils (1:9.18.18-0ubuntu0.22.04.1) ...
Processing triggers for libc-bin (2.35-0ubuntu3.4) ...
Processing triggers for man-db (2.10.2-1) ...
Errors were encountered while processing:
 consul
E: Sub-process /usr/bin/dpkg returned an error code (1)
Error during Update --- Exit Code: 100

There are an error during update          
Please check Output here or Logfile
`

**Comment by BassT23** [comment]
The problem is; the script run in subshell in the host. 
Because of that, the script is not interactive.

If anybody know, how to hold the script interactive, please give me a hint :)

**Comment by jermudgeon** [comment]
I believe the approach would be to trigger the underlying update job as
*non-interactive*

**Comment by BassT23** [comment]
please try out latest beta. There I disable "Interactive Mode".

You can update to beta with ```update beta -up```

```update -up``` will bring you back to master

**Comment by BassT23** [comment]
Problem:
The script now run in headless mode, but if there come interactive questions from another script, how to automatically answer with default?

**Comment by BassT23** [comment]
now I have the same problem, ...

headless mode don`t work here. Will look how to fix this ;)

**Comment by BassT23** [comment]
fixed for VMs with ssh connection,
will try to fix it containers soon

**Comment by BassT23** [comment]
please test latest beta with `update beta -up` and give feedback ;)

**Comment by BassT23** [comment]
fixed in latest release (v4.0)

**Comment by jeremy-preseem** [comment]
@BassT23 Still having an issue in 4.0:

`
     https://github.com/BassT23/Proxmox
     ____
    / __ \_________  _  ______ ___  ____  _  __
   / /_/ / ___/ __ \| |/_/ __ `__ \/ __ \| |/_/
  / ____/ /  / /_/ />  </ / / / / / /_/ />  <
 /_/   /_/   \____/_/|_/_/ /_/ /_/\____/_/|_|
      __  __          __      __
     / / / /___  ____/ /___ _/ /____  ____
    / / / / __ \/ __  / __ `/ __/ _ \/ __/
   / /_/ / /_/ / /_/ / /_/ / /_/  __/ /
   \____/ .___/\____/\____/\__/\___/_/
       /_/

Last modification (on GitHub): 2024-02-17T09:59:03Z

  Version overview
           Local / Server

  Updater: 4.0
  Extras:  1.8.2 / 1.8.3
  Config:  1.3.1
  Welcome: 1.3.4
  Check:   1.4.6`

`[Info] Updating LXC 113 : plexhost           
                                                      
--- APT UPDATE ---
Hit:1 http://download.zerotier.com/debian/jammy jammy InRelease
Hit:2 https://apt.releases.hashicorp.com jammy InRelease
Hit:3 http://archive.ubuntu.com/ubuntu jammy InRelease 
Get:4 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]
Get:5 http://archive.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Fetched 229 kB in 2s (92.1 kB/s)   
Reading package lists...
W: http://download.zerotier.com/debian/jammy/dists/jammy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
W: https://apt.releases.hashicorp.com/dists/jammy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.

--- APT UPGRADE ---                   
Reading package lists...              
Building dependency tree...                  
Reading state information...            
Calculating upgrade...                
The following packages will be upgraded: 
  consul dnsmasq tcpdump
3 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 68.9 MB/68.9 MB of archives.
After this operation, 5,504 kB of additional disk space will be used.
Get:1 https://apt.releases.hashicorp.com jammy/main amd64 consul amd64 1.18.0-1 [68.4 MB]
Get:2 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 tcpdump amd64 4.99.1-3ubuntu0.2 [501 kB]
dpkg-preconfigure: unable to re-open stdin: No such file or directory
Fetched 68.9 MB in 8s (8,378 kB/s)              
(Reading database ... 23996 files and directories currently installed.)
Preparing to unpack .../tcpdump_4.99.1-3ubuntu0.2_amd64.deb ...
Unpacking tcpdump (4.99.1-3ubuntu0.2) over (4.99.1-3ubuntu0.1) ...
Preparing to unpack .../consul_1.18.0-1_amd64.deb ...
Unpacking consul (1.18.0-1) over (1.17.3-1) ...                                                              
Preparing to unpack .../dnsmasq_2.90-0ubuntu0.22.04.1_all.deb ...
Unpacking dnsmasq (2.90-0ubuntu0.22.04.1) over (2.86-1.1ubuntu0.5) ...
Setting up tcpdump (4.99.1-3ubuntu0.2) ...                                                                   
                                                                                                             
Configuration file '/etc/apparmor.d/usr.bin.tcpdump' 
 ==> Modified (by you or by a script) since installation.                                                    
 ==> Package distributor has shipped an updated version.                                                     
   What would you like to do about it ?  Your options are:               
    Y or I  : install the package maintainer's version                                                                                                                                                                    
    N or O  : keep your currently-installed version
      D     : show the differences between the versions                                                      
      Z     : start a shell to examine the situation  
 The default action is to keep your current version.
*** usr.bin.tcpdump (Y/I/N/O/D/Z) [default=N] ? dpkg: error processing package tcpdump (--configure):        
 end of file on stdin at conffile prompt
Setting up consul (1.18.0-1) ...
Setting up dnsmasq (2.90-0ubuntu0.22.04.1) ...                                                               

Configuration file '/etc/dnsmasq.conf'
 ==> Modified (by you or by a script) since installation.                                                    
 ==> Package distributor has shipped an updated version.                                                     
   What would you like to do about it ?  Your options are:                                                   
    Y or I  : install the package maintainer's version                                                       
    N or O  : keep your currently-installed version   
      D     : show the differences between the versions                                                      
      Z     : start a shell to examine the situation                                                         
 The default action is to keep your current version.                                                         
*** dnsmasq.conf (Y/I/N/O/D/Z) [default=N] ? dpkg: error processing package dnsmasq (--configure):           
 end of file on stdin at conffile prompt              
Processing triggers for man-db (2.10.2-1) ...
Errors were encountered while processing:             
 tcpdump          
 dnsmasq                                                                                                     
E: Sub-process /usr/bin/dpkg returned an error code (1) 
Error during Update --- Exit Code: 100                                                                       
                                                                                                             
There are an error during update                                                                             
Please check Output here or Logfile
`

**Comment by cypromis** [comment]
Same Problem in my case caused by manualy adjusted php.ini file

**Comment by jermudgeon** [comment]
Some improvement on -s mode but still having issues with the latest updates when grub chokes on a specific device (requiring interactive prompting by the user). It also appears that silent mode is ignoring the "don't start LXC" flag.

**Comment by BassT23** [comment]
pls try out latest develop version ;) with

`update develop -up`

**Comment by jeremy-preseem** [comment]
I think this can be closed.
